FROM maven:3.8.1-jdk-11 as build
WORKDIR /build
COPY ./pom.xml .
COPY ./ms-eureka-server ./ms-eureka-server
COPY ./ms-cloud-gateway ./ms-cloud-gateway
COPY ./msclientes ./msclientes
COPY ./mscartoes ./mscartoes
COPY ./msavaliadorcredito ./msavaliadorcredito
RUN mvn clean package -DskipTests

FROM openjdk:11.0.9

WORKDIR /app
COPY --from=build ./build/msclientes/target/*.jar ./app.jar

ARG EUREKA_SERVER_PORT=8761

ENTRYPOINT ["java", "-jar", "app.jar"]
