application:
  title: Microservico mensageiro do projeto de estudo MS
  version: 1.0.0

# IMPORTANT! USADO PARA REGISTRO NO GATEWAY E LOADBALANCER
spring:
  application:
    name: msmensageiro

# vai subir o microservico em uma porta randomica ao inves da 8080
# dentro do eureka server
server:
  port: 0

# indicar ao cliente para apontar para configuracoes do eurika server
eureka:
  client:
    service-url:
# defaultZone, trocar localhost da url http://localhost:8761/eureka pelo --name do container se estiver usando docker
      defaultZone: http://localhost:8761/eureka

# instanceid no eurika de forma dinamica no dashboard
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

# expoe endpoint para actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

# definicao das filas e exchanges que este projeto ira interagir

mq:
  queues:
    admin: admin.input
    finance: finance.input
    marketing: marketing.input
    handshake: mensageiro.handshake.input
  exchanges:
    ms:
      direct:
        exchangeDefault: exchange-default.input
  routingKey:
    admin: adminRK
    finance: financeRK
    marketing: marketingRK