application:
  title: Microservico Invoice Manager
  version: 1.0.0

# IMPORTANT! USADO PARA REGISTRO NO GATEWAY E LOADBALANCER
spring:
  application:
    name: jcv-microservice-invoice-manager

# configura porta padrao de recebimento das requisicoes no gateway
server:
  port: 0

